# Generated by Django 2.1.3 on 2019-01-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_in_meters', models.FloatField()),
                ('weight_in_kg', models.FloatField()),
                ('measured_at', models.DateField()),
            ],
        ),
    ]
