# Generated by Django 2.1.3 on 2019-01-22 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_auto_20190122_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmimeasurement',
            name='measured_at',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date created'),
        ),
    ]
